############# English navigation ##############

# main menu
# [[main]]
# name = "Home"
# url = "/"
# weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "News"
url = "/news"
weight = 2

[[main]]
name = "Contact"
weight = 2

[[main]]
parent = "Contact"
name = "Contact Us"
url = "/contact"
weight = 2

[[main]]
name = "Crew"
url = "/authors"
weight = 2

[[main]]
name = "Cast"
url = "/cast"
weight = 2

[[main]]
name = "Instagram"
parent = "Contact"
url = "https://www.instagram.com/inmymindseye.film?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw=="
weight = 2

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Campaing"
url = "/campaing"
weight = 2
