############# English navigation ##############

# main menu
# [[main]]
# name = "Home"
# url = "/"
# weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "News"
url = "/news"
weight = 2

[[main]]
name = "Contact"
url = "/contact"
weight = 2

[[main]]
name = "Crew"
url = "/authors"
weight = 2

[[main]]
name = "Cast"
url = "/cast"
weight = 2

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Campaing"
url = "/campaing"
weight = 2
